# ===============================
# DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:postgresql://db:5432/hafalat
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================

server.port=8080
